env:
  - HEAD="$(git rev-parse HEAD)"

services:
  - docker

install:
#  - docker build -t alphaz .
  - docker pull alpine:latest

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag alpine narmour/alphaz-user-image:$HEAD
#  - docker tag alphaz narmour/alphaz-user-image:$HEAD
#  - docker tag alphaz narmour/alphaz-user-image:latest
#  - docker push narmour/alphaz-user-image:$HEAD
#  - docker push narmour/alphaz-user-image:latest
