env:
  - TAG="$(git rev-parse HEAD)"

services:
  - docker

install:
  - docker build -t alphaz .

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag alphaz narmour/alphaz-user-image:$TAG
  - docker tag alphaz narmour/alphaz-user-image:latest
  - docker push narmour/alphaz-user-image:$TAG
  - docker push narmour/alphaz-user-image:latest
